### PR TITLE
fix: css generation logic

### LINKED ISSUE #16: Dynamic styling based on data from props isn't parsed properly
**Describe the bug**
When more that one style is applied based upon data from props, only the first one is parsed and the rest are ignored.

**Screenshots**

**Code:**

**Output:**
When `props.primary` is `true`, only the first style is applied i.e. `background-color: blue;` but the second one is ignored.

**Expected behavior**
For the above example, `background-color: blue; color: white;` is the final style that's expected.

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Brave

### PR DESCRIPTION
**Pull request by jyash97**
# Description

Currently, the CSS generated logic fails when we add multiple dynamic properties. The reason being we are not generating the right format of array required by `styled` template literal of `styled-component` which breaks the styles.  

Fixes #16 

`Note:` this PR was created based on the consideration that the main function of `getHydratedTemplateString`  is to replace the tailwind class with the correct CSS value.

____
### Explanation of the changes:

Consider I am having the below styles: 

```
const Container = styled.div`
  .text-red-600;
  margin-top: ${(props) => props.margin};
  background: ${(props) => (props.error ? 'red' : 'black')};
  border: ${(props) => (props.border ? '2px solid black' : 'none')};
 .p-2
`
```

So the template literal will break wherever functions are present and pass those functions on the subsequent arguments.

In `styledWrapper` we will get the following first argument:

image

After passing these strings in `getHydratedTemplateString` we return the following strings to be passed in `styled.attr` from `styled-component`

image

And also pass all the expressions added in the CSS. Now `styled-components` will take care of adding the styles to the DOM and combining them with the correct expression.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Currently, I generated a build and copied that file in the App itself and tested by importing `styledWrapper` but `styled.div` was getting errors but when I tested with `styled('div')` it seems to work fine.

Tested with below code: 
```
const Banner = styled('div')`
  .text-red-600;
  margin-top: ${(props) => props.margin};
  background: ${(props) => (props.error ? 'red' : 'black')};
  border: ${(props) => (props.border ? '2px solid black' : 'none')};
  .p-6;
`;

const App = () => {
  const [a, setA] = React.useState(true);
  return (
    <>
      <Banner
        error={a}
        border={a}
        onClick={() => {
          setA(!a);
        }}
        margin='40px'
      >
        hello
      </Banner>
    </>
  );
};
```

Testing Video: https://www.loom.com/share/3e13ea376ec24ffb8321940d8c1a2c84

<details>
  <summary>Lib file that I used to check working</summary>

 ```
var getHydratedTemplateString = function getHydratedTemplateString(strings) {
  var sanitizedStyles = strings.map(function (stringsPart) {
    var classes = stringsPart.split(';');
    return classes
      .map(function (style) {
        if (style.trim().startsWith('.')) {
          return cssGen.genCSS(style.trim()).trim().replace(';;', ';');
        }

        return style;
      })
      .join(';');
  });
  return sanitizedStyles;
};

var styledWrapper = function styledWrapper(tag) {
  return function (strings) {
    var hydratedTemplateString = getHydratedTemplateString(strings);
    for (
      var _len = arguments.length,
        expressions = new Array(_len > 1 ? _len - 1 : 0),
        _key = 1;
      _key < _len;
      _key++
    ) {
      expressions[_key - 1] = arguments[_key];
    }

    return styled(tag)(hydratedTemplateString, ...expressions);
  };
};
```

</details>

# Issues faced:

- [x]  Need to test things with object pattern i.e `styled.div`
- [x]  Need to test `styled(Banner)` pattern.
- [x] Test swind classes

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/styled/styled.tsx [hunk 1]
```diff
@@ -9,32 +9,30 @@ const customConfig = windowObj?.__STYLED_WIND_CUSTOM_CONFIG__ || {};
 const config = generateStylesJS(customConfig);
 const cssGen = new CSSGen(config);
 
-const getHydratedTemplateString = (strings: TemplateStringsArray) => {
+const getHydratedTemplateString = (strings: TemplateStringsArray): any => {
```
Comment (ameerthehacker) [inline src/styled/styled.tsx:12]: @jyash97 this looks great, can you please separate this into a util function and write test for the same, so that this won't regress. Also add comment in that test to point to this particular issue.

**Review by ameerthehacker — CHANGES_REQUESTED** [review]

File: src/styled/styled.tsx (hunk 1 above)
Comment (jyash97) [reply src/styled/styled.tsx]: Done 👍

File: src/utils/getHydratedTemplateString.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
+import { CSSGen } from '../services/css-gen/css-gen';
+import generateStylesJS from './generateStylesJS';
```
Comment (ameerthehacker) [inline src/utils/getHydratedTemplateString.ts:2]: @jyash97 everything looks good, one final change I would suggest is that to follow the file naming scheme of `generate-styles-js.js` rather than `generateStyleJS.js` as it can cause issues in case insensitive filesystems.

File: src/utils/getHydratedTemplateString.spec.ts [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    const generatedStyles = getHydratedTemplateString`
+        .p-2;
+        .mt-2;
+      `;
+
+    const expectedStyles = getStringTemplate`
+        padding: 0.5rem;
+        margin-top: 0.5rem;
+      `;
+    expect(hasDifferentStyles(generatedStyles, expectedStyles)).toBeFalsy();
```
Comment (ameerthehacker) [inline src/utils/getHydratedTemplateString.spec.ts:51]: Loved this testing style ❤️

File: src/utils/getHydratedTemplateString.ts (hunk 2 above)
Comment (jyash97) [reply src/utils/getHydratedTemplateString.ts:2]: This file existed already and the naming scheme follows the same pattern in the `utils` folder

File: src/utils/getHydratedTemplateString.spec.ts (hunk 3 above)
Comment (jyash97) [reply src/utils/getHydratedTemplateString.spec.ts:51]: Thanks :) 
Wasnt super sure if this was the correct way to test but glad that you liked it

File: src/utils/getHydratedTemplateString.ts (hunk 2 above)
Comment (ameerthehacker) [reply src/utils/getHydratedTemplateString.ts:2]: ohh ok got it, then we will handle that in a separate issue and PR

**Comment by ameerthehacker** [comment]
@jyash97 if you have tested it locally and if it works I can merge.

**Comment by jyash97** [comment]
> @jyash97 if you have tested it locally and if it works I can merge.

@ameerthehacker  I have tested it locally and it works well for the example. You can also see the working here:
https://www.loom.com/share/2720d838bc8b40b89ba49e38e3582a1c

**Review by ameerthehacker — APPROVED** [review]
LGTM

**Comment by ameerthehacker** [comment]
> > @jyash97 if you have tested it locally and if it works I can merge.
> 
> @ameerthehacker  I have tested it locally and it works well for the example. You can also see the working here:
> https://www.loom.com/share/2720d838bc8b40b89ba49e38e3582a1c

Awesome thanks for the contribution

**Comment by ameerthehacker** [comment]
@jyash97 thanks for your hard work. This has been released in v0.0.0-beta.12
